# Generated by Django 3.1.5 on 2021-07-04 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20210704_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
